name: ECB sync
on:
  schedule:
  - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  ecb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget sed tree

      - name: add license to urls and download
        run: |
          mkdir ecb && cd ecb
          wget -nv --content-disposition https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
          wget -nv --content-disposition https://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip
          wget -nv --content-disposition https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
      - name: list files
        run: |
          tree

      - name: dump env
        run: |
          env |sort
          pwd
  
      # Setup rclone config from GitHub Secrets
      - name: Setup rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          rclone listremotes
          rclone ls gdrive:
            

