name: Geonames sync
on:
  schedule:
  - cron: '20 5 5 * *' # 5th day of the month
  workflow_dispatch:

jobs:
  geonames:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget s3cmd sed tree

      - name: add license to urls and download
        run: |
          mkdir geonames && cd geonames
          cat ../geonames-urls.txt | xargs -n1 -P2 wget -nv --content-disposition 

      - name: list files
        run: |
          tree

    # Setup rclone config from GitHub Secrets
      - name: Setup rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          pwd
          mkdir -p ~/.config/rclone/
          wget -q https://downloads.rclone.org/v1.66.0/rclone-v1.66.0-linux-amd64.deb
          sudo dpkg -i rclone-v1.66.0-linux-amd64.deb
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          rclone -v sync geonames gdrive:geonames/
