name: Geonames sync
on:
  schedule:
  - cron: '20 5 5 * *' # 5th day of the month
  workflow_dispatch:

jobs:
  geonames:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget s3cmd sed tree

      - name: add license to urls and download
        run: |
          mkdir geonames && cd geonames
          cat ../geonames-urls.txt | xargs -n1 -P2 wget -nv --content-disposition 

      - name: list files
        run: |
          tree

      - name: upload files
        uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKETNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRETKEY }}
          AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'geonames'      # optional: defaults to entire repository
          DEST_DIR: 'Geonames'
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
