name: Maxmind sync
on:
  schedule:
  - cron: '20 5 * * *'
  workflow_dispatch:

jobs:
  maxmind:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget s3cmd sed tree

      - name: add license to urls and download
        run: |
          mkdir maxmind && cd maxmind
          cat ../maxmind-urls.txt | sed 's/YOUR_LICENSE_KEY/${{ secrets.MAXMIND_KEY }}/g' | xargs -n1 -P2 wget -nv --content-disposition 

      - name: list files
        run: |
          tree

 
    # Setup rclone config from GitHub Secrets
      - name: Setup rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          pwd
          mkdir -p ~/.config/rclone/
          wget -q https://downloads.rclone.org/v1.66.0/rclone-v1.66.0-linux-amd64.deb
          sudo dpkg -i rclone-v1.66.0-linux-amd64.deb
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          rclone sync maxmind gdrive:maxmind/ -v
