name: Maxmind sync
on:
  schedule:
  - cron: '20 4 * * *'
  workflow_dispatch:

jobs:
  maxmind:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget s3cmd sed tree

      - name: add license to urls and download
        run: |
          mkdir maxmind && cd maxmind
          cat ../maxmind-urls.txt | sed 's/YOUR_LICENSE_KEY/${{ secrets.MAXMIND_KEY }}/g' | xargs -n1 -P2 wget -nv --content-disposition 

      - name: list files
        run: |
          tree

      - name: upload files
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKETNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRETKEY }}
          AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'maxmind'      # optional: defaults to entire repository
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
