name: Ofcom Codelist sync
on:
  schedule:
  - cron: '20 5 5 * *' # 5th day of the month
  workflow_dispatch:

jobs:
  codelist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add packages
        run: sudo apt-get update && sudo apt-get -y install curl wget s3cmd sed tree

      - name: add license to urls and download
        run: |
          mkdir codelist && cd codelist
          #cat ../ofcom-urls.txt | xargs -n1 -P2 wget -v --content-disposition 
          # seeing 403 errors, need to see the errors etc.
          curl -Sv "https://www.ofcom.org.uk/siteassets/resources/documents/phones-telecoms-and-internet/information-for-industry/numbering/regular-updates/telephone-numbers/codelist.zip" > codelist.zip
          file codelist.zip # get magic for type identification
          cat codelist.zip |strings # see if there is anything readable

      - name: list files
        run: |
          tree


    # Setup rclone config from GitHub Secrets
      - name: Setup rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          pwd
          mkdir -p ~/.config/rclone/
          wget -q https://downloads.rclone.org/v1.66.0/rclone-v1.66.0-linux-amd64.deb
          sudo dpkg -i rclone-v1.66.0-linux-amd64.deb
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          rclone sync codelist gdrive:codelist/ -v

